version: "3.8"
services:
  app:
    container_name: takoyaki-app
    depends_on:
      - database
    build: ./
    env_file: .env
    ports:
      - $API_PORT:8080
    volumes:
      - takoyaki-app-pipe:/var/run/takoyaki
  database:
    container_name: takoyaki-database
    image: postgres:13.1
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - takoyaki-database-data:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
  proxy:
    container_name: takoyaki-proxy
    depends_on:
      - app
      - database
    image: nginx:mainline-alpine
    ports:
      - 8000:80
    volumes:
      - ./dev/proxy:/etc/nginx/templates
volumes:
  takoyaki-app-pipe: {}
  takoyaki-database-data: {}
