version: "3.8"
services:
  api:
    container_name: takoyaki-api
    depends_on:
      - database
    build: ./
    env_file: .env
    ports:
      - 3000:8080
    volumes:
      - api-pipe:/var/run/takoyaki
  database:
    container_name: takoyaki-database
    image: postgres:13.1
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
  frontend:
    container_name: takoyaki-frontend
    build: ../takoyaki-frontend
    ports:
      - 3001:8080
  proxy:
    container_name: takoyaki-proxy
    depends_on:
      - api
      - frontend
    image: nginx:mainline-alpine
    ports:
      - 8000:80
    volumes:
      - ./dev/proxy:/etc/nginx/templates
volumes:
  api-pipe: {}
  database-data: {}
