#!/bin/sh

# dev scripts for takoyaki
# run this script from project root

echo "Purging database, docker containers and vm, are you sure [y/n]"
read confirm
[ ! "$confirm" = "y" ] && exit 0

echo 'stopping containers...'
docker-compose down

echo 'removing db data...'
docker volume rm takoyaki-backend_database-data

echo 'destroying all vms...'
for domain in $(virsh -c qemu:///system list --name); do
    virsh -c qemu:///system shutdown "$domain"
    virsh -c qemu:///system destroy "$domain"
    virsh -c qemu:///system undefine --nvram "$domain"
    virsh -c qemu:///system vol-delete --pool vps "${domain}-vol"
done

